# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  boardingservice:
    image: alessiacontenti/boardingservice
    restart: always
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    ports: 
      - '9090:80'

  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   container_name: 'rabbitmq'
  #   ports:
  #     - '5672:5672'
  #     - '15672:15672'