# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "aco/dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore **/*.sln
    - name: Build
      run: dotnet build **/*.sln --no-restore
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: PocAirportSystem/BoardingService/bin/Debug/net7.0
  docker:
    name: docker build and push
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: build-artifact
        path: PocAirportSystem/BoardingService/bin/Debug/net7.0
    - name: Build the Docker image
      working-directory: PocAirportSystem/BoardingService
      run: docker build . --file Dockerfile --tag alessiacontenti/boardingservice:$(date +%s)
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: "{{defaultContext}}:PocAirportSystem/BoardingService"
        push: true
        tags: alessiacontenti/boardingservice:latest
